[satellite]
name = "KubOS Sat"
ip = "ip.of.the.sat"
config-path = "/path/to/KubOS-config.toml"

[file-client]
binary-path = "/path/to/kubos-file-client/binary"

[shell-client]
binary-path = "/path/to/kubos-shell-client/binary"
file-list-directories = ["/home/kubos/", "/var/log/", "/upgrade/"]
